/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.organillama;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author Mau
 */
public class OrganillamaPrincipal extends javax.swing.JFrame {
    
    public boolean maximizado;
    
    private Integer value;
    
    public int xMouse,yMouse;
    
    private String fondo;
    
    private boolean panelVerOn;
    
    /**
     * Creates new form OrganillamaPrincipal
     */
    public OrganillamaPrincipal() {
        fondo = "src//main//java//Imagenes//fondo3.png";
        initComponents();
        
        inicializarFrameXCodigo();
        
        
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        panelFondoContenedor = new javax.swing.JPanel();
        panelBarraSuperior = new javax.swing.JPanel();
        lblCerrar = new javax.swing.JLabel();
        lblMaximizar = new javax.swing.JLabel();
        lblMinimizar = new javax.swing.JLabel();
        panelPrincipal = new javax.swing.JPanel();
        panelReloj = new org.organillama.PanelRound();
        lblHora = new javax.swing.JLabel();
        lblRelojIcono = new javax.swing.JLabel();
        lblRelojFecha = new javax.swing.JLabel();
        panelCalendario = new org.organillama.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        panelActividades = new org.organillama.PanelRound();
        lblVer = new javax.swing.JLabel();
        lblCrear = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblConfiguracion = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        labelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFondo.setMinimumSize(new java.awt.Dimension(1280, 720));
        panelFondo.setOpaque(false);
        panelFondo.setPreferredSize(new java.awt.Dimension(1280, 720));
        panelFondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelFondoMouseClicked(evt);
            }
        });
        panelFondo.setLayout(new javax.swing.BoxLayout(panelFondo, javax.swing.BoxLayout.PAGE_AXIS));

        panelFondoContenedor.setBackground(new java.awt.Color(0, 0, 0));
        panelFondoContenedor.setAlignmentX(0.0F);
        panelFondoContenedor.setAlignmentY(0.0F);
        panelFondoContenedor.setMinimumSize(new java.awt.Dimension(1280, 720));
        panelFondoContenedor.setOpaque(false);
        panelFondoContenedor.setPreferredSize(new java.awt.Dimension(1280, 720));

        panelBarraSuperior.setBackground(new Color(0,0,0,100));
        panelBarraSuperior.setMaximumSize(new java.awt.Dimension(5000, 40));
        panelBarraSuperior.setMinimumSize(new java.awt.Dimension(1280, 40));
        panelBarraSuperior.setPreferredSize(new java.awt.Dimension(1280, 40));
        panelBarraSuperior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelBarraSuperiorMouseDragged(evt);
            }
        });
        panelBarraSuperior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelBarraSuperiorMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelBarraSuperiorMousePressed(evt);
            }
        });

        lblCerrar.setBackground(new Color(0,0,0,0));
        lblCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrar.setOpaque(true);
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCerrarMouseExited(evt);
            }
        });

        lblMaximizar.setBackground(new Color(0,0,0,0));
        lblMaximizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMaximizar.setOpaque(true);
        lblMaximizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMaximizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMaximizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMaximizarMouseExited(evt);
            }
        });

        lblMinimizar.setBackground(new Color(0,0,0,0));
        lblMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimizar.setOpaque(true);
        lblMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelBarraSuperiorLayout = new javax.swing.GroupLayout(panelBarraSuperior);
        panelBarraSuperior.setLayout(panelBarraSuperiorLayout);
        panelBarraSuperiorLayout.setHorizontalGroup(
            panelBarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBarraSuperiorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblMaximizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        panelBarraSuperiorLayout.setVerticalGroup(
            panelBarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBarraSuperiorLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(panelBarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaximizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        panelPrincipal.setBackground(new java.awt.Color(255, 153, 153));
        panelPrincipal.setAlignmentX(0.0F);
        panelPrincipal.setAlignmentY(0.0F);
        panelPrincipal.setMinimumSize(new java.awt.Dimension(1280, 680));
        panelPrincipal.setOpaque(false);
        panelPrincipal.setPreferredSize(new java.awt.Dimension(1280, 680));

        panelReloj.setBackground(new Color(255,255,255,40));
        panelReloj.setMinimumSize(new java.awt.Dimension(530, 170));
        panelReloj.setPreferredSize(new java.awt.Dimension(530, 170));
        panelReloj.setRoundBottomLeft(30);
        panelReloj.setRoundBottomRight(30);
        panelReloj.setRoundTopLeft(30);
        panelReloj.setRoundTopRight(30);

        lblHora.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        lblHora.setForeground(new java.awt.Color(204, 255, 255));
        lblHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHora.setMaximumSize(new java.awt.Dimension(510, 150));
        lblHora.setMinimumSize(new java.awt.Dimension(340, 100));
        lblHora.setName(""); // NOI18N
        lblHora.setPreferredSize(new java.awt.Dimension(340, 100));

        lblRelojIcono.setMinimumSize(new java.awt.Dimension(120, 120));

        lblRelojFecha.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblRelojFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRelojFecha.setMaximumSize(new java.awt.Dimension(510, 45));
        lblRelojFecha.setMinimumSize(new java.awt.Dimension(340, 30));
        lblRelojFecha.setPreferredSize(new java.awt.Dimension(340, 30));

        javax.swing.GroupLayout panelRelojLayout = new javax.swing.GroupLayout(panelReloj);
        panelReloj.setLayout(panelRelojLayout);
        panelRelojLayout.setHorizontalGroup(
            panelRelojLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRelojLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelRelojLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRelojFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                    .addComponent(lblHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addComponent(lblRelojIcono, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );
        panelRelojLayout.setVerticalGroup(
            panelRelojLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRelojLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addComponent(lblRelojFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRelojLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblRelojIcono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );

        panelCalendario.setBackground(new Color(255,255,255,40));
        panelCalendario.setMinimumSize(new java.awt.Dimension(530, 650));
        panelCalendario.setPreferredSize(new java.awt.Dimension(530, 650));
        panelCalendario.setRoundBottomLeft(30);
        panelCalendario.setRoundBottomRight(30);
        panelCalendario.setRoundTopLeft(30);
        panelCalendario.setRoundTopRight(30);

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setText("Buscar Fecha");

        jDateChooser1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N

        jCalendar1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N

        javax.swing.GroupLayout panelCalendarioLayout = new javax.swing.GroupLayout(panelCalendario);
        panelCalendario.setLayout(panelCalendarioLayout);
        panelCalendarioLayout.setHorizontalGroup(
            panelCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCalendarioLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
            .addGroup(panelCalendarioLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCalendarioLayout.setVerticalGroup(
            panelCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCalendarioLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelActividades.setBackground(new Color(255,255,255,40));
        panelActividades.setMinimumSize(new java.awt.Dimension(720, 660));
        panelActividades.setOpaque(true);
        panelActividades.setPreferredSize(new java.awt.Dimension(720, 660));
        panelActividades.setRoundBottomLeft(30);
        panelActividades.setRoundBottomRight(30);
        panelActividades.setRoundTopLeft(30);
        panelActividades.setRoundTopRight(30);

        lblVer.setBackground(new Color(0,0,255));
        lblVer.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblVer.setForeground(new java.awt.Color(255, 255, 255));
        lblVer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVer.setText("Ver");
        lblVer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVer.setMaximumSize(new java.awt.Dimension(120, 60));
        lblVer.setMinimumSize(new java.awt.Dimension(80, 40));
        lblVer.setOpaque(true);
        lblVer.setPreferredSize(new java.awt.Dimension(80, 40));
        lblVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVerMouseClicked(evt);
            }
        });

        lblCrear.setBackground(new Color(0,0,255,0));
        lblCrear.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblCrear.setForeground(new java.awt.Color(255, 255, 255));
        lblCrear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCrear.setText("Crear");
        lblCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCrear.setMaximumSize(new java.awt.Dimension(120, 60));
        lblCrear.setMinimumSize(new java.awt.Dimension(80, 40));
        lblCrear.setOpaque(true);
        lblCrear.setPreferredSize(new java.awt.Dimension(80, 40));
        lblCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCrearMouseClicked(evt);
            }
        });

        lblUsuario.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblUsuario.setText("Nom Usuario");

        lblConfiguracion.setBackground(new Color(0,0,0,0));
        lblConfiguracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblConfiguracion.setMaximumSize(new java.awt.Dimension(100, 100));
        lblConfiguracion.setMinimumSize(new java.awt.Dimension(50, 50));
        lblConfiguracion.setOpaque(true);
        lblConfiguracion.setPreferredSize(new java.awt.Dimension(50, 50));
        lblConfiguracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblConfiguracionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblConfiguracionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblConfiguracionMouseExited(evt);
            }
        });

        content.setBackground(new java.awt.Color(255, 0, 0));
        content.setMinimumSize(new java.awt.Dimension(700, 570));
        content.setOpaque(false);
        content.setPreferredSize(new java.awt.Dimension(700, 570));
        content.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout panelActividadesLayout = new javax.swing.GroupLayout(panelActividades);
        panelActividades.setLayout(panelActividadesLayout);
        panelActividadesLayout.setHorizontalGroup(
            panelActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelActividadesLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelActividadesLayout.createSequentialGroup()
                        .addComponent(lblVer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lblCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        panelActividadesLayout.setVerticalGroup(
            panelActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActividadesLayout.createSequentialGroup()
                .addGroup(panelActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelActividadesLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblConfiguracion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelActividadesLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panelActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, 0)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelReloj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCalendario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addComponent(panelActividades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(panelReloj, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(panelCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, 478, Short.MAX_VALUE))
                    .addComponent(panelActividades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout panelFondoContenedorLayout = new javax.swing.GroupLayout(panelFondoContenedor);
        panelFondoContenedor.setLayout(panelFondoContenedorLayout);
        panelFondoContenedorLayout.setHorizontalGroup(
            panelFondoContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBarraSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelFondoContenedorLayout.setVerticalGroup(
            panelFondoContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoContenedorLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelBarraSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        panelFondo.add(panelFondoContenedor);
        panelFondoContenedor.getAccessibleContext().setAccessibleName("");

        getContentPane().add(panelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        labelFondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelFondoMouseClicked(evt);
            }
        });
        getContentPane().add(labelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelFondoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelFondoMouseClicked

    }//GEN-LAST:event_labelFondoMouseClicked

    private void panelFondoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFondoMouseClicked
       
    }//GEN-LAST:event_panelFondoMouseClicked

    private void lblCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseEntered
        CambioImagen(lblCerrar,"src//main//java//Imagenes//btnCerrarCian.png",80);
        
        
    }//GEN-LAST:event_lblCerrarMouseEntered

    private void lblCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseExited
        
        CambioImagen(lblCerrar,"src//main//java//Imagenes//btnCerrarBlanco.png",0);
        
        
    }//GEN-LAST:event_lblCerrarMouseExited

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void lblMaximizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMaximizarMouseEntered
        
        CambioImagen(lblMaximizar,"src//main//java//Imagenes//btnMaximizarCian.png",80); 
        
       
    }//GEN-LAST:event_lblMaximizarMouseEntered

    private void lblMaximizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMaximizarMouseExited
        
        CambioImagen(lblMaximizar,"src//main//java//Imagenes//btnMaximizarBlanco.png",0); 
        
       
    }//GEN-LAST:event_lblMaximizarMouseExited

    private void lblMaximizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMaximizarMouseClicked
       extender();
    }//GEN-LAST:event_lblMaximizarMouseClicked

    private void lblMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseEntered
        CambioImagen(lblMinimizar,"src//main//java//Imagenes//btnMinimizarCian.png",80);
        
        
    }//GEN-LAST:event_lblMinimizarMouseEntered

    private void lblMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseExited
        
        CambioImagen(lblMinimizar,"src//main//java//Imagenes//btnMinimizarBlanco.png",0); 
        
       
    }//GEN-LAST:event_lblMinimizarMouseExited

    private void lblMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseClicked
       this.setState(ICONIFIED);
    }//GEN-LAST:event_lblMinimizarMouseClicked

    private void panelBarraSuperiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBarraSuperiorMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_panelBarraSuperiorMousePressed

    private void panelBarraSuperiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBarraSuperiorMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_panelBarraSuperiorMouseDragged

    private void panelBarraSuperiorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBarraSuperiorMouseClicked
       if(evt.getClickCount()==2){
            extender();
        }
    }//GEN-LAST:event_panelBarraSuperiorMouseClicked

    private void lblConfiguracionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConfiguracionMouseEntered
        CambioImagen(lblConfiguracion, "src//main//java//Imagenes//configuracionCian.png", 80);
    }//GEN-LAST:event_lblConfiguracionMouseEntered

    private void lblConfiguracionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConfiguracionMouseExited
       CambioImagen(lblConfiguracion, "src//main//java//Imagenes//configuracion.png", 0);
    }//GEN-LAST:event_lblConfiguracionMouseExited

    private void lblConfiguracionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConfiguracionMouseClicked
        Configuracion btnConfig = new Configuracion(this);
        btnConfig.setVisible(true);
    }//GEN-LAST:event_lblConfiguracionMouseClicked

    private void lblVerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVerMouseClicked
        if(panelVerOn==false){
        imagen(labelFondo,fondo);
        panelVer ver= new panelVer();
        panelCrear crear= new panelCrear(this);
        mostrarPanel(ver,crear);
        }
    }//GEN-LAST:event_lblVerMouseClicked

    private void lblCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCrearMouseClicked
        if(panelVerOn==true){
        panelVer ver= new panelVer();
        panelCrear crear= new panelCrear(this);
        mostrarPanel(ver,crear);
        imagen(labelFondo,fondo);
        }
    }//GEN-LAST:event_lblCrearMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrganillamaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrganillamaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrganillamaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrganillamaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrganillamaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel content;
    private com.toedter.calendar.JCalendar jCalendar1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelFondo;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblConfiguracion;
    private javax.swing.JLabel lblCrear;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblMaximizar;
    private javax.swing.JLabel lblMinimizar;
    private javax.swing.JLabel lblRelojFecha;
    private javax.swing.JLabel lblRelojIcono;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblVer;
    private org.organillama.PanelRound panelActividades;
    private javax.swing.JPanel panelBarraSuperior;
    private org.organillama.PanelRound panelCalendario;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelFondoContenedor;
    private javax.swing.JPanel panelPrincipal;
    private org.organillama.PanelRound panelReloj;
    // End of variables declaration//GEN-END:variables
    public void inicializarFrameXCodigo(){
        this.setSize(1280, 720);
        this.setPreferredSize(new Dimension(1280,720));
        maximizado=false;
        
        labelFondo.setBounds(0,0,1280,720);
        labelFondo.setMaximumSize(new Dimension(1280,720));
        imagen(labelFondo,fondo);
        
        imagen(lblCerrar, "src//main//java//Imagenes//btnCerrarBlanco.png");
        imagen(lblMaximizar, "src//main//java//Imagenes//btnMaximizarBlanco.png");
        imagen(lblMinimizar, "src//main//java//Imagenes//btnMinimizarBlanco.png");
        imagen(lblConfiguracion,"src//main//java//Imagenes//configuracion.png");
        
        panelVerOn = false;
        panelVer ver= new panelVer();
        panelCrear crear= new panelCrear(this);
        mostrarPanel(ver,crear);
        
        tiempo();
    }
/*
Inicio Métodos    
*/
    
public void extender(){//maximizar o minimizar el frame
   if(maximizado == false){ 
    
        GraphicsEnvironment env =
        GraphicsEnvironment.getLocalGraphicsEnvironment();
        this.setMaximizedBounds(env.getMaximumWindowBounds());
        this.setExtendedState(this.getExtendedState() | this.MAXIMIZED_BOTH);
        
        ajustar(this.getWidth(),this.getHeight());
        
        
        maximizado = true;
        
        imagen(labelFondo,fondo);
   }else{
        this.setSize(new Dimension(1280,720));
        
        ajustar(this.getWidth(),this.getHeight());
        
        this.setLocationRelativeTo(null);
        maximizado = false; 
        imagen(labelFondo,fondo);
   } 
}

public void ajustar(int x, int y){ //cambia el tamaño de: jframe y jpanel para maximizar o minimizar
    
        labelFondo.setPreferredSize(new Dimension(x, y));
        labelFondo.setBounds(0,0, this.getWidth(), this.getHeight());
        
    
        panelFondo.setPreferredSize(new Dimension(x, y));
        panelFondo.setSize(new Dimension(x, y));
        panelFondo.setBounds(0,0,x, y );
        
        panelFondoContenedor.setPreferredSize(new Dimension(x, y));
        panelFondoContenedor.setSize(new Dimension(x, y));
        panelFondoContenedor.setBounds(0,0,x, y );
        
        ajustarFuentes(lblHora);
        ajustarFuentes(lblRelojFecha);
        ajustarFuentes(lblRelojIcono);
}

public void imagen(JLabel lbl,String ruta){ //cambiar imágenes de las etiquetas
    ImageIcon img = new ImageIcon(ruta);
    Icon icono = new ImageIcon(img.getImage().getScaledInstance(lbl.getWidth(), lbl.getHeight(),Image.SCALE_DEFAULT));
    lbl.setIcon(icono);
    lbl.repaint();
    
}

public void CambioImagen(JLabel lbl,String ruta,int intensidad){ //cambia la imagen y actualiza el fondo
    
    lbl.setBackground(new Color(0,0,0,intensidad));
    
    lbl.setIcon(null);
    ImageIcon img = new ImageIcon(ruta);
    Icon icono = new ImageIcon(img.getImage().getScaledInstance(lbl.getWidth(), lbl.getHeight(),Image.SCALE_DEFAULT));
    lbl.setIcon(icono);
    lbl.repaint();
    
    imagen(labelFondo,fondo);
    
}

public void tiempo() 
    {
        
        
        imagen(labelFondo,fondo);
        
        Timer timer;
        
        ActionListener actionListener = new ActionListener() 
        {
            @Override
            public void actionPerformed(ActionEvent e) 
            {
                Date date = new Date();
                
                DateFormat timeFormat = new SimpleDateFormat("hh:mm:ss a");
                
                String time = timeFormat.format(date);
                
                timeFormat = new SimpleDateFormat("dd MMMM yyyy");
                
                lblRelojFecha.setText(timeFormat.format(date));
                
                DateFormat get_status = new SimpleDateFormat("HH");
                
                String status = get_status.format(date);
                
                value = Integer.valueOf(status);
                
                 if((value>=06)&&(value<13))
                {                    
                    imagen(lblRelojIcono,"src//main//java//Imagenes//mañana.png");
                    
                    imagen(labelFondo,fondo);
                    
                    lblRelojFecha.setForeground(Color.white);
                    
                    
                }
                if((value>=13)&&(value<20))
                {                    
                    imagen(lblRelojIcono,"src//main//java//Imagenes//tarde.png");
                    
                    imagen(labelFondo,fondo);
                    
                    lblRelojFecha.setForeground(Color.white);
                    
                    lblHora.setForeground(Color.white);
                    
                    
                }
                if((value>=20)&&(value<=24)||(value>=00)&&(value<06))
                
                {
                    imagen(lblRelojIcono,"src//main//java//Imagenes//noche.png");
                    
                    imagen(labelFondo,fondo);
                    
                    lblRelojFecha.setForeground(Color.white);
                    
                    lblHora.setForeground(Color.white);

                }
                
                lblHora.setText(time);
                
            }
        };
        
        timer = new Timer(1000, actionListener);
        
        timer.setInitialDelay(0);
        
        timer.start();
    }

public void ajustarFuentes(JLabel lbl ){
    if(maximizado==false){
        lbl.setFont(new Font("Roboto",Font.BOLD, lbl.getFont().getSize()*3/2)); 
        lbl.setPreferredSize(new Dimension(lbl.getWidth()*3/2,lbl.getHeight()*3/2));
        lbl.setSize(new Dimension(lbl.getWidth()*3/2,lbl.getHeight()*3/2));
        
    }else{
        lbl.setFont(new Font("Roboto",Font.BOLD,lbl.getFont().getSize()*2/3));
        lbl.setPreferredSize(new Dimension(lbl.getWidth()*3/2,lbl.getHeight()*2/3));
        lbl.setSize(new Dimension(lbl.getWidth()*3/2,lbl.getHeight()*2/3));
        
    }
}

private void ShowPanel(JPanel p){
        p.setSize(790,740);
        p.setLocation(0,0);
        
        content.removeAll();
        content.add(p,BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
        
    }
public void mostrarPanel(JPanel pan1,JPanel pan2){
    if(panelVerOn==false){
        lblCrear.setBackground(new Color(0,0,255,0));
        lblVer.setBackground(new Color(0,0,255));
        ShowPanel(pan1);
        panelVerOn =true;
        
    }else{
        lblCrear.setBackground(new Color(0,0,255));
        lblVer.setBackground(new Color(0,0,255,0));
        ShowPanel(pan2);
        panelVerOn=false;
    }
}

/*
Fin Métodos    
*/    


}
