/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.organillama;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.Timer;

/**
 *
 * @author Mau
 */
public class OrganillamaPrincipalRepuesto extends javax.swing.JFrame {
    
    public boolean maximizado;
    Integer value;
    int xMouse,yMouse;
    /**
     * Creates new form OrganillamaPrincipal
     */
    public OrganillamaPrincipalRepuesto() {
        initComponents();
        inicializarFrameXCodigo();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        panelFondoContenedor = new javax.swing.JPanel();
        panelBarraSuperior = new javax.swing.JPanel();
        lblCerrar = new javax.swing.JLabel();
        lblMaximizar = new javax.swing.JLabel();
        lblMinimizar = new javax.swing.JLabel();
        panelPrincipal = new javax.swing.JPanel();
        panelReloj = new org.organillama.PanelRound();
        lblHora = new javax.swing.JLabel();
        lblRelojIcono = new javax.swing.JLabel();
        lblRelojFecha = new javax.swing.JLabel();
        panelRound2 = new org.organillama.PanelRound();
        panelRound3 = new org.organillama.PanelRound();
        labelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFondo.setMinimumSize(new java.awt.Dimension(1280, 720));
        panelFondo.setOpaque(false);
        panelFondo.setPreferredSize(new java.awt.Dimension(1280, 720));
        panelFondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelFondoMouseClicked(evt);
            }
        });
        panelFondo.setLayout(new javax.swing.BoxLayout(panelFondo, javax.swing.BoxLayout.PAGE_AXIS));

        panelFondoContenedor.setBackground(new java.awt.Color(0, 0, 0));
        panelFondoContenedor.setAlignmentX(0.0F);
        panelFondoContenedor.setAlignmentY(0.0F);
        panelFondoContenedor.setMinimumSize(new java.awt.Dimension(1280, 720));
        panelFondoContenedor.setOpaque(false);
        panelFondoContenedor.setPreferredSize(new java.awt.Dimension(1280, 720));

        panelBarraSuperior.setBackground(new Color(0,0,0,60));
        panelBarraSuperior.setMaximumSize(new java.awt.Dimension(5000, 40));
        panelBarraSuperior.setMinimumSize(new java.awt.Dimension(1280, 40));
        panelBarraSuperior.setPreferredSize(new java.awt.Dimension(1280, 40));
        panelBarraSuperior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelBarraSuperiorMouseDragged(evt);
            }
        });
        panelBarraSuperior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelBarraSuperiorMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelBarraSuperiorMousePressed(evt);
            }
        });

        lblCerrar.setBackground(new Color(0,0,0,0));
        lblCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrar.setOpaque(true);
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCerrarMouseExited(evt);
            }
        });

        lblMaximizar.setBackground(new Color(0,0,0,0));
        lblMaximizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMaximizar.setOpaque(true);
        lblMaximizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMaximizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMaximizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMaximizarMouseExited(evt);
            }
        });

        lblMinimizar.setBackground(new Color(0,0,0,0));
        lblMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimizar.setOpaque(true);
        lblMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelBarraSuperiorLayout = new javax.swing.GroupLayout(panelBarraSuperior);
        panelBarraSuperior.setLayout(panelBarraSuperiorLayout);
        panelBarraSuperiorLayout.setHorizontalGroup(
            panelBarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBarraSuperiorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblMaximizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        panelBarraSuperiorLayout.setVerticalGroup(
            panelBarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBarraSuperiorLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(panelBarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaximizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        panelPrincipal.setBackground(new java.awt.Color(255, 153, 153));
        panelPrincipal.setAlignmentX(0.0F);
        panelPrincipal.setAlignmentY(0.0F);
        panelPrincipal.setMinimumSize(new java.awt.Dimension(1280, 680));
        panelPrincipal.setOpaque(false);
        panelPrincipal.setPreferredSize(new java.awt.Dimension(1280, 680));

        panelReloj.setBackground(new Color(0,0,0,80));
        panelReloj.setMinimumSize(new java.awt.Dimension(530, 170));
        panelReloj.setPreferredSize(new java.awt.Dimension(530, 170));
        panelReloj.setRoundBottomLeft(30);
        panelReloj.setRoundBottomRight(30);
        panelReloj.setRoundTopLeft(30);
        panelReloj.setRoundTopRight(30);

        lblHora.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        lblHora.setForeground(new java.awt.Color(204, 255, 255));
        lblHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHora.setMaximumSize(new java.awt.Dimension(510, 150));
        lblHora.setMinimumSize(new java.awt.Dimension(340, 100));
        lblHora.setName(""); // NOI18N
        lblHora.setPreferredSize(new java.awt.Dimension(340, 100));

        lblRelojIcono.setMinimumSize(new java.awt.Dimension(120, 120));

        lblRelojFecha.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblRelojFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRelojFecha.setMaximumSize(new java.awt.Dimension(510, 45));
        lblRelojFecha.setMinimumSize(new java.awt.Dimension(340, 30));
        lblRelojFecha.setPreferredSize(new java.awt.Dimension(340, 30));

        javax.swing.GroupLayout panelRelojLayout = new javax.swing.GroupLayout(panelReloj);
        panelReloj.setLayout(panelRelojLayout);
        panelRelojLayout.setHorizontalGroup(
            panelRelojLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRelojLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelRelojLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRelojFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addComponent(lblHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(lblRelojIcono, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );
        panelRelojLayout.setVerticalGroup(
            panelRelojLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRelojLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addComponent(lblRelojFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRelojLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblRelojIcono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );

        panelRound2.setBackground(new Color(0,0,0,80));
        panelRound2.setMinimumSize(new java.awt.Dimension(530, 650));
        panelRound2.setPreferredSize(new java.awt.Dimension(530, 650));
        panelRound2.setRoundBottomLeft(30);
        panelRound2.setRoundBottomRight(30);
        panelRound2.setRoundTopLeft(30);
        panelRound2.setRoundTopRight(30);

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelRound3.setBackground(new Color(0,0,0,80));
        panelRound3.setMinimumSize(new java.awt.Dimension(720, 660));
        panelRound3.setPreferredSize(new java.awt.Dimension(720, 660));
        panelRound3.setRoundBottomLeft(30);
        panelRound3.setRoundBottomRight(30);
        panelRound3.setRoundTopLeft(30);
        panelRound3.setRoundTopRight(30);

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelReloj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRound2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addComponent(panelRound3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(panelReloj, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, 478, Short.MAX_VALUE))
                    .addComponent(panelRound3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout panelFondoContenedorLayout = new javax.swing.GroupLayout(panelFondoContenedor);
        panelFondoContenedor.setLayout(panelFondoContenedorLayout);
        panelFondoContenedorLayout.setHorizontalGroup(
            panelFondoContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBarraSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelFondoContenedorLayout.setVerticalGroup(
            panelFondoContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoContenedorLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelBarraSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        panelFondo.add(panelFondoContenedor);
        panelFondoContenedor.getAccessibleContext().setAccessibleName("");

        getContentPane().add(panelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        labelFondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelFondoMouseClicked(evt);
            }
        });
        getContentPane().add(labelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelFondoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelFondoMouseClicked

    }//GEN-LAST:event_labelFondoMouseClicked

    private void panelFondoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFondoMouseClicked
       
    }//GEN-LAST:event_panelFondoMouseClicked

    private void lblCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseEntered
        CambioImagen(lblCerrar,"src//main//java//Imagenes//btnCerrarCian.png",80);
        
        
    }//GEN-LAST:event_lblCerrarMouseEntered

    private void lblCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseExited
        
        CambioImagen(lblCerrar,"src//main//java//Imagenes//btnCerrarBlanco.png",0);
        
        
    }//GEN-LAST:event_lblCerrarMouseExited

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void lblMaximizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMaximizarMouseEntered
        
        CambioImagen(lblMaximizar,"src//main//java//Imagenes//btnMaximizarCian.png",80); 
        
       
    }//GEN-LAST:event_lblMaximizarMouseEntered

    private void lblMaximizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMaximizarMouseExited
        
        CambioImagen(lblMaximizar,"src//main//java//Imagenes//btnMaximizarBlanco.png",0); 
        
       
    }//GEN-LAST:event_lblMaximizarMouseExited

    private void lblMaximizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMaximizarMouseClicked
       extender();
    }//GEN-LAST:event_lblMaximizarMouseClicked

    private void lblMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseEntered
        CambioImagen(lblMinimizar,"src//main//java//Imagenes//btnMinimizarCian.png",80);
        
        
    }//GEN-LAST:event_lblMinimizarMouseEntered

    private void lblMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseExited
        
        CambioImagen(lblMinimizar,"src//main//java//Imagenes//btnMinimizarBlanco.png",0); 
        
       
    }//GEN-LAST:event_lblMinimizarMouseExited

    private void lblMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseClicked
       this.setState(ICONIFIED);
    }//GEN-LAST:event_lblMinimizarMouseClicked

    private void panelBarraSuperiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBarraSuperiorMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_panelBarraSuperiorMousePressed

    private void panelBarraSuperiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBarraSuperiorMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_panelBarraSuperiorMouseDragged

    private void panelBarraSuperiorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBarraSuperiorMouseClicked
       if(evt.getClickCount()==2){
            extender();
        }
    }//GEN-LAST:event_panelBarraSuperiorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrganillamaPrincipalRepuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrganillamaPrincipalRepuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrganillamaPrincipalRepuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrganillamaPrincipalRepuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrganillamaPrincipalRepuesto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelFondo;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblMaximizar;
    private javax.swing.JLabel lblMinimizar;
    private javax.swing.JLabel lblRelojFecha;
    private javax.swing.JLabel lblRelojIcono;
    private javax.swing.JPanel panelBarraSuperior;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelFondoContenedor;
    private javax.swing.JPanel panelPrincipal;
    private org.organillama.PanelRound panelReloj;
    private org.organillama.PanelRound panelRound2;
    private org.organillama.PanelRound panelRound3;
    // End of variables declaration//GEN-END:variables
    public void inicializarFrameXCodigo(){
        this.setSize(1280, 720);
        this.setPreferredSize(new Dimension(1280,720));
        maximizado=false;
        
        labelFondo.setBounds(0,0,1280,720);
        labelFondo.setMaximumSize(new Dimension(1280,720));
        imagen(labelFondo,"src//main//java//Imagenes//fondo2.png");
        
        imagen(lblCerrar, "src//main//java//Imagenes//btnCerrarBlanco.png");
        imagen(lblMaximizar, "src//main//java//Imagenes//btnMaximizarBlanco.png");
        imagen(lblMinimizar, "src//main//java//Imagenes//btnMinimizarBlanco.png");
        
        tiempo();
    }
/*
Inicio Métodos    
*/
    
public void extender(){//maximizar el frame
   if(maximizado == false){ 
    
        GraphicsEnvironment env =
        GraphicsEnvironment.getLocalGraphicsEnvironment();
        this.setMaximizedBounds(env.getMaximumWindowBounds());
        this.setExtendedState(this.getExtendedState() | this.MAXIMIZED_BOTH);
     
        labelFondo.setPreferredSize(new Dimension(this.getWidth(), this.getHeight()));
        labelFondo.setBounds(0,0, this.getWidth(), this.getHeight());
        
    
        panelFondo.setPreferredSize(new Dimension(this.getWidth(), this.getHeight()));
        panelFondo.setSize(new Dimension(this.getWidth(), this.getHeight()));
        panelFondo.setBounds(0,0,this.getWidth(), this.getHeight() );
        
        panelFondoContenedor.setPreferredSize(new Dimension(this.getWidth(), this.getHeight()));
        panelFondoContenedor.setSize(new Dimension(this.getWidth(), this.getHeight()));
        panelFondoContenedor.setBounds(0,0,this.getWidth(), this.getHeight() );
        maximizado = true;
        
        imagen(labelFondo,"src//main//java//Imagenes//fondo2.png");
   }else{
        this.setSize(new Dimension(1280,720));
        labelFondo.setPreferredSize(new Dimension(this.getWidth(), this.getHeight()));
        labelFondo.setBounds(0,0, this.getWidth(), this.getHeight());
        
    
        panelFondo.setPreferredSize(new Dimension(this.getWidth(), this.getHeight()));
        panelFondo.setSize(new Dimension(this.getWidth(), this.getHeight()));
        panelFondo.setBounds(0,0,this.getWidth(), this.getHeight() );
        
        panelFondoContenedor.setPreferredSize(new Dimension(this.getWidth(), this.getHeight()));
        panelFondoContenedor.setSize(new Dimension(this.getWidth(), this.getHeight()));
        panelFondoContenedor.setBounds(0,0,this.getWidth(), this.getHeight() );
        imagen(labelFondo,"src//main//java//Imagenes//fondo2.png");
        this.setLocationRelativeTo(null);
        
        maximizado = false; 
   } 
}

public void imagen(JLabel lbl,String ruta){ //cambiar imágenes de las etiquetas
    ImageIcon img = new ImageIcon(ruta);
    Icon icono = new ImageIcon(img.getImage().getScaledInstance(lbl.getWidth(), lbl.getHeight(),Image.SCALE_DEFAULT));
    lbl.setIcon(icono);
    lbl.repaint();
    
}

public void CambioImagen(JLabel lbl,String ruta,int intensidad){ //cambia la imagen y actualiza el fondo
    
    lbl.setBackground(new Color(0,0,0,intensidad));
    
    lbl.setIcon(null);
    ImageIcon img = new ImageIcon(ruta);
    Icon icono = new ImageIcon(img.getImage().getScaledInstance(lbl.getWidth(), lbl.getHeight(),Image.SCALE_DEFAULT));
    lbl.setIcon(icono);
    lbl.repaint();
    
    imagen(labelFondo,"src//main//java//Imagenes//fondo2.png");
    
}

public void tiempo() 
    {
        
        
        imagen(labelFondo,"src//main//java//Imagenes//fondo2.png");
        
        Timer timer;
        
        ActionListener actionListener = new ActionListener() 
        {
            @Override
            public void actionPerformed(ActionEvent e) 
            {
                Date date = new Date();
                
                DateFormat timeFormat = new SimpleDateFormat("hh:mm:ss a");
                
                String time = timeFormat.format(date);
                
                timeFormat = new SimpleDateFormat("dd MMMM yyyy");
                
                lblRelojFecha.setText(timeFormat.format(date));
                
                DateFormat get_status = new SimpleDateFormat("HH");
                
                String status = get_status.format(date);
                
                value = Integer.valueOf(status);
                
                 if((value>=00)&&(value<13))
                {                    
                    imagen(lblRelojIcono,"src//main//java//Imagenes//mañana.png");
                    
                    imagen(labelFondo,"src//main//java//Imagenes//fondo2.png");
                    
                    lblRelojFecha.setForeground(Color.white);
                    
                    
                }
                if((value>=13)&&(value<18))
                {                    
                    imagen(lblRelojIcono,"src//main//java//Imagenes//tarde.png");
                    
                    imagen(labelFondo,"src//main//java//Imagenes//fondo2.png");
                    
                    lblRelojFecha.setForeground(Color.white);
                    
                    lblHora.setForeground(Color.white);
                    
                    
                }
                if((value>=18)&&(value<=24))
                {
                    imagen(lblRelojIcono,"src//main//java//Imagenes//noche.png");
                    
                    imagen(labelFondo,"src//main//java//Imagenes//fondo2.png");
                    
                    lblRelojFecha.setForeground(Color.white);
                    
                    lblHora.setForeground(Color.white);

                }
                
                lblHora.setText(time);
                
            }
        };
        
        timer = new Timer(1000, actionListener);
        
        timer.setInitialDelay(0);
        
        timer.start();
    }
    
/*
Fin Métodos    
*/    
}
