/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.organillama;

import java.awt.Color;

/**
 *
 * @author Mau
 */
public class panelVer extends javax.swing.JPanel {

    /**
     * Creates new form panelVer
     */
    public panelVer() {
        
        initComponents();
        agregarActividades(8);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        contenidoScroll = new javax.swing.JPanel();

        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setHorizontalScrollBar(null);
        jScrollPane1.setOpaque(false);

        contenidoScroll.setOpaque(false);
        contenidoScroll.setLayout(new java.awt.GridLayout(0, 1, 10, 10));
        jScrollPane1.setViewportView(contenidoScroll);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenidoScroll;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

public void agregarActividades(int n){
    for (int i=0;i<n;i++){
        contenidoScroll.add(new Actividad());
    }
}
}
